"""edit-order-table

Revision ID: b67393795dca
Revises: 0b259fb76b06
Create Date: 2023-04-26 19:39:08.139627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67393795dca'
down_revision = '0b259fb76b06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'created_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('created_date', sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###
