"""add_status_order

Revision ID: 0b259fb76b06
Revises: 3655666de5c4
Create Date: 2023-04-26 18:41:49.329907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b259fb76b06'
down_revision = '3655666de5c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categoryrequest', 'store_owner_id')
    op.add_column('order', sa.Column('status', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'status')
    op.add_column('categoryrequest', sa.Column('store_owner_id', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
